apiVersion: v1
kind: Service
metadata:
  name: {{ include "klarsicht.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klarsicht.agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "klarsicht.agent.selectorLabels" . | nindent 4 }}
