{{- if and .Values.agent.tls.caBundle (not .Values.agent.tls.caBundleSecret.name) (not .Values.agent.tls.caBundleConfigMap.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klarsicht.fullname" . }}-agent-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klarsicht.agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.agent.tls.caBundle | indent 4 }}
{{- end }}
