apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "klarsicht.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klarsicht.labels" . | nindent 4 }}
automountServiceAccountToken: true
